import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";
import type { Metadata } from "next";
import { fontMont, sanSwah, inter, roboto } from "./fonts";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import "./globals.css";
export const metadata: Metadata = {
  title: "Habibullah Khan - portfolio",
  viewport: { width: "device-width", initialScale: 1 },
  icons: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${fontMont.variable} ${roboto.variable} ${sanSwah.variable} ${inter.variable}`}
    >
      <body className="select-none flex items-center  text-dark w-full min-h-[98vh] dark:!bg-dark  flex-col box-border">
        <Script id="theme-switcher" strategy="beforeInteractive">{
          // On page load or when changing themes, best to add inline in `head` to avoid FOUC
          `if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
  document.documentElement.classList.add('dark')
} else {
  document.documentElement.classList.remove('dark')}
  console.log("darkMode adeed-----")

  `
        }</Script>

        <NavBar className=" grow-0 dark:bg-dark dark:text-light dark"></NavBar>
        <main className={`bg-light w-full grow border-box dark:!bg-dark`}>
          {children}
        </main>
        <Footer className="grow-0 dark:!bg-dark"></Footer>
        <Analytics />
      </body>
    </html>
  );
}
